runtime: go115

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_idle_instances: 1

main: ./cmd/appd/

handlers:
  - url: /.*
    secure: always
    script: auto

  - url: /swagger
    static_dir: swagger